---
- name: Installation extensions apache guacamole
  hosts: guacamole_servers
  become: true

  - tasks:
    - name:
          - name: Download Guacamole server source
      get_url:
        url: "https://downloads.apache.org/guacamole/1.5.5/binary/guacamole-auth-jdbc-1.5.5.tar.gz"
        dest: /tmp/guacamole-auth-jdbc-1.5.5.tar.gz

    - name: Extract Guacamole server
      unarchive:
        src: /tmp/guacamole-auth-jdbc-1.5.5.tar.gz
        dest: /tmp/guacamole-auth-jdbc-1.5.5/
        remote_src: yes

    - name: Move MySQL connector file to lib directory
      copy:
       src: /tmp/guacamole-auth-jdbc-1.5.5/mysql/guacamole-auth-jdbc-mysql-1.5.5.jar
       dest: /etc/guacamole/extensions/guacamole-auth-jdbc-mysql-1.5.5.jar
       remote_src: yes


    - name: Download connector Mysql
      get_url:
        url: "https://dev.mysql.com/get/Downloads/Connector-J/mysql-connector-j-9.1.0.tar.gz"
        dest: /tmp/mysql-connector-j-9.1.0.tar.gz

    - name: Extract Guacamole server
      unarchive:
        src: /tmp/mysql-connector-j-9.1.0.tar.gz
        dest: /tmp/mysql-connector-j-9.1.0/
        remote_src: yes

    - name: Move MySQL connector file to lib directory
      copy:
       src: /tmp/mysql-connector-j-9.1.0/mysql-connector-j-9.1.0.jar
       dest: /etc/guacamole/lib/mysql-connector-j-9.1.0.jar
       remote_src: yes



