---
- name: Install and Configure Splunk
  hosts: prometheus_servers
  become: true
  gather_facts: true

  tasks:
  - name: Mettre a jour les paquets
    apt:
      name: "*"
      update_cache: yes
      state: latest
      autoclean: yes
      autoremove: yes
