version: '3'

services:
  suricata:
    image: jasonish/suricata:latest
    container_name: suricata
    ports:
      - "3500:3500"
    volumes:
      - /var/log/suricata:/var/log/suricata
    networks:
      - security_network

networks:
  security_network:
