version: '3'

services:
  nagios:
    image: nagios/nagioscore:latest
    container_name: nagios
    ports:
      - "8080:80"
    environment:
      NAGIOS_ADMIN_USER: nagiosadmin
      NAGIOS_ADMIN_PASSWORD: nagiosadminpassword
    networks:
      - monitoring_network

networks:
  monitoring_network:
