---
- name: Configure Databases for Snort
  hosts: snort_servers
  become: true

  tasks:
  - name: Secure MariaDB Installation
    shell: |
      mysql -e "SET PASSWORD FOR 'root'@'localhost' = PASSWORD('rootpassword');"
      mysql -e "DELETE FROM mysql.user WHERE User='';"
      mysql -e "DELETE FROM mysql.db WHERE Db='test' OR Db='test\\_%';"
      mysql -e "FLUSH PRIVILEGES;"
    args:
      executable: /bin/bash

  - name: Create Snort database
    mysql_db:
      name: snort
      state: latest
      
  - name: Create Snort database user
    mysql_user:
      name: snort_user
      password: "snortpassword"
      priv: "snort.*:ALL"
      state: present

  - name: Download BASE
    get_url:
      url: https://sourceforge.net/projects/secureideas/files/latest/download/base-1.4.5.tar.gz
      dest: /tmp/base-1.4.5.tar.gz

  - name: Extract BASE
    unarchive:
      src: /tmp/base-1.4.5.tar.gz
      dest: /var/www/html/
      remote_src: yes

  - name: Set Apache permissions
  file:
    path: /var/www/html/base-1.4.5
    state: directory
    mode: "0755"
    owner: www-data
    group: www-data

  - name: Restart Apache
    systemd:
      name: apache2
      state: restarted

  - name: Configure Snort to log to database
    lineinfile:
      path: /etc/snort/snort.conf
      insertafter: EOF
      line: "output database: log, mysql, user=snort_user password=snortpassword dbname=snort host=localhost"

  - name: Check BASE installation
    uri:
      url: "http://localhost/base"
      return_content: yes
    register: base_response

  - name: Print BASE response
    debug:
      var: base_response.content
