version: '3'

services:
  bind9:
    image: sameersbn/bind:9.16.3
    container_name: bind9
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    environment:
      - BIND9_ADMIN_PASSWORD=bindpassword
    networks:
      - dns_network

networks:
  dns_network:
