all:
  hosts:
    snort_server:
      ansible_host: localhost
      ansible_user: root
      ansible_become: true 
      ansible_become_method: sudo 
      ansible_become_password: root
      ansible_python_interpreter: /usr/bin/python3

    client_machine:
      ansible_host: 192.168.153.129
      ansible_user: root
      ansible_password: root 
      ansible_become: true
      ansible_become_method: sudo
