- name: Installation et configuration de Suricata
  hosts: suricata_server
  become: yes

  tasks:
    - name: Mettre a jour les paquets
      apt:
        update_cache: yes

    - name: Installer Suricata
      apt:
        name: suricata
        state: present

    - name: Configurer HOME_NET dans suricata.yaml
      lineinfile:
        path: /etc/suricata/suricata.yaml
        regexp: '^HOME_NET:.*'
        line: 'HOME_NET: "[192.168.153.0/24]"'

    - name: Creer un fichier de regles de base
      copy:
        dest: /etc/suricata/rules/suricata.rules
        content: |
          alert icmp any any -> any any (msg: "ICMP Ping Detected"; sid:1000001; rev:1;)

    - name: Activer Suricata en mode IDS
      command: suricata -c /etc/suricata/suricata.yaml -i ens33 -D

    - name: Verifier installation de Suricata
      command: suricata --build-info
